### PR TITLE
Create invite command as mentioned in issue #7

### PR DESCRIPTION
**Pull request by waspothegreat**

### CODE REVIEW

**Comment by Hoi15A** [comment]
The command currently fails with the following error:
```
(node:13073) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed.timestamp: Could not parse Mon Aug 13 2018. Should be ISO8601.
    at item.request.gen.end (/home/austin/git/forks/simple-discord-bot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/austin/git/forks/simple-discord-bot/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13073) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13073) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

There's 2 ways to fix it:
- Pass an iso datestring instead of a normal one
- Use my [messageSender.js](https://github.com/Hoi15A/simple-discord-bot/blob/master/lib/messageSender.js) file which has a function standardResponse() that takes 4 parameters: 
1. The message object
2. The response text
3. The info variable (used for colour and whatnot)
4. A thumbnail image url

This function takes care of building the embed and making sure default values are set if missing. An example of usage can be seen in [rename.js](https://github.com/Hoi15A/simple-discord-bot/blob/master/commands/rename.js)

**Review by Hoi15A — CHANGES_REQUESTED** [review]
(see above comment)

**Comment by waspothegreat** [comment]
Yes I know I could have used your [messageSender.js](https://github.com/Hoi15A/simple-discord-bot/blob/master/lib/messageSender.js) file but I find typing the embed out in raw json easier

**Comment by Hoi15A** [comment]
image

- Markdown has a missing `)`
- `Today at * today at` (honestly just use the standard message sender function, there's a reason I wrote it. All you gotta do is include `./lib/messageSender.js` as seen in other files)
- "Invite to the bot" sounds kinda weird. Change to "Invite the bot"

**Pull request merged**
